version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
  pad:
    build: .
    container_name: pad
    restart: always
    ports:
      - "8080:8080"
    environment:
      REDIS_URI: redis://redis:6379/0
      PAD_SALT: secret_salt
