[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/coreos/bbolt"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.0"

[[constraint]]
  name = "github.com/speps/go-hashids"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/logutils"

[[constraint]]
  branch = "master"
  name = "github.com/matryer/is"
